# Generated by Django 3.1.2 on 2020-10-10 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmy_web', '0003_auto_20201004_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField(default=0)),
                ('gatunek', models.PositiveSmallIntegerField(choices=[(3, 'Drama'), (2, 'Comedy'), (1, 'Horror'), (4, 'Sci-fi'), (0, 'Different')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='additional',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmy_web.additionalinfo'),
        ),
    ]
